### ISSUE TITLE
"String index out of range: 0" error in RegistryStamping.

### ISSUE THREAD

**Issue by Angular-Angel** [Peatral/EmbersConstruct#11]
So I'm trying to start the game with roughly a billion mods, including this one and Just Enough IDs (To manage them all), and I get an error:

[crash-2020-09-26_13.31.36-client.txt](https://github.com/Peatral/EmbersConstruct/files/5287229/crash-2020-09-26_13.31.36-client.txt)

There's the crash report. If you need me to check anything else, just ask.

**Comment by Peatral** [comment]
Interesting, I thought I had this fixed in the newest release but it seems like my mind playee tricks on me. Well, I fixed it but after the latest release.
I fixed it with c9002ba9f6ac44ff192cb9c3ebbb61164f4375a9 so I will make a new release real soon (I already delayed it because I've currently got less time than half a year ago). I have to check a few things and maybe I release it tomorrow.

**Comment by Angular-Angel** [comment]
Oh, also! I changed the line: "B:dustStamping=true" in the config to false, and that also fixed the problem, or so it seems.

**Comment by Peatral** [comment]
Yeah that leads to a situation where the problematic bit gets skipped.
I will release the next version soon and I'd like to ask you if you could test it.
Here is the file (of course you have to extract the zip):
[embersconstruct-1.12.2-1.3.0.zip](https://github.com/Peatral/EmbersConstruct/files/5288121/embersconstruct-1.12.2-1.3.0.zip)

**Comment by Angular-Angel** [comment]
Alright, will do.

**Comment by Angular-Angel** [comment]
Yup, that does it. Problem solved.
