### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Biviho** [Peatral/EmbersConstruct#12]
hi, it seems that embers construct throws an exeption during the game loading

here the pastebin [https://pastebin.com/WGqjjsqS](https://pastebin.com/WGqjjsqS)

I can tell that the mod did worked at the beginning, but at some point i don't really know if it is a mod or a config that i changed, that caused this crash.
It's a pretty chonky modpack, so i will see if i can exclude some mods in the next weeks (can't really do that earlyer), but in the meantime i will leave the issue here, maybe is something that you can already fix

**Comment by Peatral** [comment]
Ok, so looking at the crash report, it seems that someone registers a tool material, but doesn't registers a representative item (Or registers an invalid stack). This didn't happen before because usually there is always a representative item. But I will add a check.

So it may be a different mod or a changed config of another mod. This is what I can tell...

**Comment by Biviho** [comment]
hi! glad it should be something easy to fix!
i do actually something tricky in the modpack: i disable tinkers tool and use the crafting component to craft vanilla items, maybe some mod that add their compatibility to tinkers don't do that in the right way.
when i can check i will try to exclude some mods to see if i can find the culprit

**Comment by Peatral** [comment]
Yes, it is actually quite easy to fix. Upon further investigation of the source code, I found out that Forge throws this error if the stack I am trying to get the OreDictionary ID of is empty. So a check before calling that is the right way to fix it. 
But I still wonder why a mod is registering a tool material with an empty stack or removes the representative item (so usually something like the ingot). This is quite similar to the last crash I fixed where some mod registered a fluid under an empty string (""). I just can't comprehend what the use of a fluid registered under an empty string or a tool material without a representative item is.

**Comment by Biviho** [comment]
yeah, quite trange indeed, maybe is some unused or unfinished content

**Comment by Peatral** [comment]
yeah, maybe

**Comment by Biviho** [comment]
i have found a piece of the puzzle!
it looks like when the option to enable tool parts from tinkers construct is disabled, it cause that crash.
I was trying to use just the smeltery, without any tools or modifiers and wanted to use  embers construct to get the smelting recipes for the stamper

**Comment by Peatral** [comment]
Ok, it is weird that disabling the tool parts at all lead to that crash and I don't get the correlation, this means maybe a deeper investigation. But knowing where it comes from is a good starting point.
One question: Were you planning to use the stamper/smeltery only for melting ores and such into ingots? I mean yeah, this mod makes it possible although that wasn't actually my intention... (But I think disabling almost every feature from TC, such as the smeltery and the toolparts, what is the use of it besides the better ore compat provided by this mod)
Also the crash should be fixed with 3f00876.

**Comment by Biviho** [comment]
well, i'm still pondering on if i actually want to keep the tools part and change all vanilla like tool and weapons to use the parts from TC or not...
basically my idea for my pack is to use the smeltery for any metal manipulation, with the aid of immersive engineering and infini-tic. Embers will be a middle-end game way of manipulating them, if i can find a way in the config to make it good from a game design standpoint, but yes, i have still to evaluate things.
at the moment, it seems that the stamper is a bit quicker in processing metals i have to see how much i can tweak things
