### ISSUE TITLE
Various stamps no longer work.

### ISSUE THREAD

**Issue by Zeitiah** [Peatral/EmbersConstruct#21]
Hello, as of Ember's Construct 1.3.5, several materials no longer have stamping recipes. Some still do work (broad axe head for example), but most stamps do not.
One that works:
![works](https://user-images.githubusercontent.com/34135692/162582047-36d0fe11-ea63-47e5-bff4-b25b96c0e8aa.PNG)

One that does not work:
![no_work](https://user-images.githubusercontent.com/34135692/162582060-96913208-f5b4-465f-adf0-025dda06cacd.PNG)

**Comment by Peatral** [comment]
Huh, that is weird, I will take a look.

**Comment by Peatral** [comment]
Fixed with 4dec5f40435f47194d884b5db59c5b60adad16ac. The problem was in a method NBT data wasn't compared and therefore all recipes with the same inputs (without nbt aka any stamp) & fluid with different output got discarded (besides the first one).

I will see if I get a hotfix out or fix #20 beforehand, we will see
