### ISSUE TITLE
Disabling Smeltery Disables many of the alloy recipes in the Mixer

### ISSUE THREAD

**Issue by Orinai** [Peatral/EmbersConstruct#5]
Just like It says, I have noticed - initially with manyllyum - that with the smeltery disabled, several of the mixer recipes disappear.

Reading through comments on curseforge, looks like you may already be aware of the issue, but reporting as a bug just to be sure

**Comment by Peatral** [comment]
Yes I am already aware of that issue. The problem is that when the smeltery gets disabled no alloying recipes are registered and therefore this mod doesn't know where to get the recipes. I may take a look at it again and try to find a good solution, because adding all the recipes by hand seems illogical for me, becausd the mod should independantly register recipes. Currently I have only the default recipes of Tinkers hard-coded. But as I said it is a hard problem, but I will try to fix it.

**Comment by Orinai** [comment]
This may be a dumb thought , but would it be easier to do the reverse, and have a config option to disable the smeltery from your end, after the recipies have been registered, instead of relying on the option in ticon's config? I immagine not, but figured even a dumb idea can sometimes start a new line of problem solving

**Comment by Peatral** [comment]
That is actually a really interesting thought. Disabling the Tinkers' smeltery module also breaks a few mods like PlusTiC and Taiga. I'm not quite sure how I would go about disabling the smeltery though. Removing all smeltery related recipes may be enough for some people, because I don't think I can easily remove already registered blocks (and that would be a quite weird thing to do anyway). The problem is that I currently see no _direct_ way to remove recipes (for example via function call) but it may be possible with reflections (changing fields in another class during runtime).

I will definitely try that out, it's a great idea I never would have thought of.

**Comment by Peatral** [comment]
The crazy thing is this actually worked. I now added the possibility to remove the different smeltery recipes:
- Alloying
- Melting
- Table & Basin Casting

If removing the Tinkers' recipes solves the problem, than this issue can be closed with 95ae839eb910a9a1c230c66f683551065b8109f9.

**Comment by Orinai** [comment]
That solves several problems actually,  since as you mentioned, disabling the smeltery breaks a number of mods! Glad it worked out!
