### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by Pival81** [Peatral/EmbersConstruct#7]
https://hastebin.com/bopigutize.rb

**Comment by Peatral** [comment]
This problem lies with Forge more or less, the last version that should work is 14.23.5.2847. After that Forge changed a few things around and I can't even get my workspace set up with one of the three newer versions (Believe me, I tried really hard but currently you find nothing on those errors during the setup). This means currently:

1. I won't update to a newer version of Forge (this error would be the only reason to update)
2. You have to use Forge 14.23.5.2847

Maybe when I get a newer version working I can try but when I can't even get it to run I can't fix anything. (This is why I leave this issue open)

Hope this satisfies you, currently I can't do more than guiding you to a working Forge version...

**Comment by Peatral** [comment]
Well I opened IntelliJ just to proof to myself that it doesn't work and now it magically works lul, an hour wasted this afternoon. But now I'm not quite sure what the actual problem is because it doesn't actually seem like anything changed.

**Comment by Pival81** [comment]
Actually, I just tried it with forge 14.23.5.2847, and it still crashes with the same exception.

**Comment by Peatral** [comment]
That is actually pretty weird...

**Comment by Peatral** [comment]
This is literally the Forge version I developed the mod in. Also the field "FACING" is there, and I don't know why this happens. I will definitely try to find out wtf is actually happening...

**Comment by Peatral** [comment]
Please tell me if this works (with any version), Forge is stealing my sanity. I can't believe how changing a version string and changing nothing at all can f*ck forge up like this.
The jar is in the zip.
[extract hotfix.zip](https://github.com/Peatral/EmbersConstruct/files/4832230/extract.hotfix.zip)

**Comment by Pival81** [comment]
It seems like it's working, but I haven't been able to run my pack yet since I have easily 300+ mods and I've run out of time. At least it's not crashing.

**Comment by Orinai** [comment]
Just to offer some additional data for cross-reference, I'm getting the same issue. Crash report linked below. haven't tried the hotfix yet, will momentarily
[https://www.dropbox.com/s/o0a11qdy3mxukby/crash-2020-06-25_12.59.52-client.txt?dl=0](url)
Only change between crash and no-crash is updating EC. forge is the saem version

**Comment by Peatral** [comment]
Ok, a friend of mine also tested it and it worked fine. I am still not quite sure what the actual reason for this bug is (When I run it in the dev environment there is no crash, but standalone there is, it's a field that should exist, etc. it's really confusing) but it seems that I fixed it. I think I will release the hotfix, it should work. But you (@Orinai) could also test it, just to be safe.

**Comment by Orinai** [comment]
I just did, and yes, the Hotfix works ^^

**Comment by Peatral** [comment]
Okay then I will publish it and close this issue...

**Comment by Peatral** [comment]
I finally know what the exact issue was: Seemingly just running the build or the jar task isn't enough because it actually does not get reobfuscated as inititally I thought. And I don't know why I had to look through half of the internet to find that I had to run reobfJar after everything.

**Comment by Orinai** [comment]
Good to know where the problem came out of
