### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Yourname942** [Peatral/EmbersConstruct#8]
Here is my latest.log:
(I wasn't able to post to pastebin, paste.ee or gist)

[latest.log](https://github.com/Peatral/EmbersConstruct/files/4842990/latest.log)

**Comment by Peatral** [comment]
This crash basically means another mod registered an ore in the OreDict literally as "dust" (why should you do that?), and because I strip it away to get the full ore name nothing is left and it crashes.
It's extremly easy to fix (fixed with c9002ba9f6ac44ff192cb9c3ebbb61164f4375a9), and therefore has no real priority to make a release for it now. You can get around with just disabling stamping recipes in the config of Embers Construct (under embersconstructsettings -> dustStamping=false). This should prevent the problematic piece of code from beeing run. I can't guarantee it though, there may be another entry in the OreDict that sucks (like "ingot", "plate", etc.), but because the dust-bit gets called after everything else it should work.
